/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mediaFilesInformation;

import java.io.File;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author rem711
 */
public class MainWindow extends javax.swing.JFrame {
    private File folder;
    private FileExplorer fileExplorer;
    private final String STATUS_DONE = "Done!";
    private final String NO_FILE = "No corresponding file found.";
    private final String STATUS_GETTING_INFO = "Getting information abour your media...";
    private final String STATUS_GENERATING_FILES = "Generating files...";
    private final String STATUS_WAITING_USER = "Waiting for a folder to begin";
    private final String INIT_FOLDER_PATH = "D:/";
    private final short TIME_GETTING_INFO = 0;
    private final short TIME_GENERATING_FILES = 1;
    private Chrono[] tabChrono;

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
        this.fileExplorer = new FileExplorer(new File(INIT_FOLDER_PATH), "media");
        this.folder = null;
        this.fileChooser.setCurrentDirectory(new java.io.File(INIT_FOLDER_PATH));
        this.fileChooser.setFileSelectionMode(javax.swing.JFileChooser.FILES_AND_DIRECTORIES);
        this.labelStatus.setText(this.STATUS_WAITING_USER);
        this.tabChrono = new Chrono[] {new Chrono(), new Chrono()};
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Media Files Information");

        buttonOpenFileChooser.setText("Choose Folder");
        buttonOpenFileChooser.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonOpenFileChooser.setMaximumSize(new java.awt.Dimension(64, 32));
        buttonOpenFileChooser.setMinimumSize(new java.awt.Dimension(64, 32));
        buttonOpenFileChooser.setPreferredSize(new java.awt.Dimension(64, 32));
        buttonOpenFileChooser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                buttonOpenFileChooserMouseReleased(evt);
            }
        });

        labelMainWindow.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMainWindow.setText("Choose the initial folder where your media are :");

        labelCredits.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelCredits.setText("Credits : Rémi Courvoisier");

        labelStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelStatus.setMaximumSize(new java.awt.Dimension(147, 16));
        labelStatus.setMinimumSize(new java.awt.Dimension(147, 16));
        labelStatus.setPreferredSize(new java.awt.Dimension(147, 16));

        labelInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelInfo.setMaximumSize(new java.awt.Dimension(147, 16));
        labelInfo.setMinimumSize(new java.awt.Dimension(147, 16));
        labelInfo.setPreferredSize(new java.awt.Dimension(147, 16));

        labelError.setForeground(new java.awt.Color(222, 22, 22));
        labelError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelError.setMaximumSize(new java.awt.Dimension(147, 16));
        labelError.setMinimumSize(new java.awt.Dimension(147, 16));
        labelError.setPreferredSize(new java.awt.Dimension(147, 16));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelMainWindow, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelCredits, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelInfo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelStatus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(buttonOpenFileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(121, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(labelError, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addComponent(labelMainWindow)
                .addGap(18, 18, 18)
                .addComponent(buttonOpenFileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(labelStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(labelCredits)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(129, Short.MAX_VALUE)
                    .addComponent(labelError, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(147, 147, 147)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonOpenFileChooserMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonOpenFileChooserMouseReleased
        if(this.fileChooser.showOpenDialog(this) == javax.swing.JFileChooser.APPROVE_OPTION) {
            this.folder = this.fileChooser.getSelectedFile();
        }
        else {
            this.folder = null;
        }
        
        if(this.folder != null && this.folder.isDirectory()) {
            this.labelStatus.setText(this.STATUS_GETTING_INFO);
            this.labelStatus.repaint();
                        
            this.fileExplorer.setInitFolder(this.folder);
            this.tabChrono[this.TIME_GETTING_INFO].setBegin();
            this.fileExplorer.populate();
            this.tabChrono[this.TIME_GETTING_INFO].setEnd();
            List<Media> medias = this.fileExplorer.getListMedias();
            
            if(medias.isEmpty()) {
                this.labelStatus.setText(this.NO_FILE);
                this.labelStatus.repaint();
            }
            else {
                this.labelStatus.setText(this.STATUS_GENERATING_FILES);
                this.labelStatus.repaint();
                this.labelInfo.setText(medias.size() + " file(s) found in " + this.tabChrono[this.TIME_GETTING_INFO].difference() + "s");
                this.labelInfo.repaint();
            }
        }
    }//GEN-LAST:event_buttonOpenFileChooserMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private final javax.swing.JButton buttonOpenFileChooser = new javax.swing.JButton();
    private final javax.swing.JFileChooser fileChooser = new javax.swing.JFileChooser();
    private final javax.swing.JLabel labelCredits = new javax.swing.JLabel();
    private final javax.swing.JLabel labelError = new javax.swing.JLabel();
    private final javax.swing.JLabel labelInfo = new javax.swing.JLabel();
    private final javax.swing.JLabel labelMainWindow = new javax.swing.JLabel();
    private final javax.swing.JLabel labelStatus = new javax.swing.JLabel();
    // End of variables declaration//GEN-END:variables
}
